#!/bin/bash

###########################################################################
##          Quenrensys, Inc. CONFIDENTIAL AND PROPRIETARY
##        This source is the sole property of Qurensys, Inc.
##      Reproduction or utilization of this source in whole or in part
##    is forbidden without the written consent of Querensys, Inc.
###########################################################################
##                 Copyright (c) 2018 Querensys, Inc.
##                           All Rights Reserved
###########################################################################

PROCESS_NAME="ffmpeg"
SCRIPT_NAME="quality"
PROCESS_FULL_PATH="$INSTALL_DIR/$PROCESS_NAME"


pid=""

function echo_copyright()
{
    echo
    echo "==================================================================="
    echo " Qty_Con v1.0"
    echo " Copyright (c) 2018 Querensys, Inc."
    echo " All Rights Reserved"
    echo "==================================================================="
}
 
getpid()
{
	pid=`pidof -x $PROCESS_NAME`
}

HQon()
{
	if [ "x$pid" = "x" ];
	then
	nohup	$PROCESS_NAME -rtsp_transport tcp -i rtsp://admin:123456@192.168.1.234:554/video1+audio1  -c:v h264_nvenc -r 30 -g 60 -force_key_frames "expr:gte(t,n_forced*2.0)" -c:a aac -b:a 128k -ar 44100 -f mpegts "udp://localhost:50000?fifo_size=10000000" > /dev/null 2>&1 &
		echo  "start HQ_$PROCESS_NAME [OK]"
	else
		echo -e "\033[01malready running... pid $pid"
		echo -e "\033[0m"
	fi
}

LQon()
{
	if [ "x$pid" = "x" ];
	then
	nohup	$PROCESS_NAME -rtsp_transport tcp -i rtsp://admin:123456@192.168.1.234:554/video1+audio1  -c:v h264_nvenc -r 30 -g 60 -force_key_frames "expr:gte(t,n_forced*2.0)" -b:v 200k -c:a aac -b:a 128k -ar 44100 -f mpegts "udp://localhost:50000?fifo_size=10000000" > /dev/null 2>&1 &
		echo  "start LQ_$PROCESS_NAME [OK]"
	else
		echo -e "\033[01malready running... pid $pid"
		echo -e "\033[0m"
	fi
}

stop()
{
	if [ "x$pid" = "x" ];
	then
		echo "$PROCESS_NAME is not running..."
	else	
		kill -15 $pid
		echo "stop $PROCESS_NAME [OK]"
		echo "$PROCESS_NAME process $pid killed"
	fi
}

status()
{
	if [ "x$pid" = "x" ];
	then 
            echo -e "$PROCESS_NAME is not running" 
	    exit 1
	else
	    echo -e "\033[01m$PROCESS_NAME is running...[pid $pid]"
	    echo "=========================="
	     cat /proc/$pid/status | grep VmPeak
	    cat /proc/$pid/status | grep VmSize
	    echo -e "\033[0m"
	    exit 0
	
	fi
}

echo_copyright
getpid



case "$1" in
	HQon)
	    stop
	    HQon
		;;
	LQon)
	    stop
    	LQon
    	;;
	stop)
		stop
		;;
	status)
		status
		;; 
	*)
		echo " Usage: ./$SCRIPT_NAME {HQon|LQon|stop|status}"
		exit 1
		;;

esac

exit 0
